### ISSUE TITLE
log.py?

### ISSUE THREAD

**Issue by UltraBob** [atlefren/pytilt#1]
Is `sudo python log.py` correct?  I don't see a log.py anywhere in the codebase, and I'm not sure I understand how that would work.  I don't have a tilt yet, I'm investigating what I could do with one, so I couldn't really test.

**Comment by UltraBob** [comment]
looking at your commit history, I suspect you mean pytilt.py

**Comment by atlefren** [comment]
Hi and thanks for catching this. The readme was unfortunately wrong, mostly because I haven't really put any effort into documenting it (as i got it working for myself, as is the case for most of my open projects).

However, if you are interested in using this I'll try to fix the documentation

**Comment by UltraBob** [comment]
Thanks!
